#!/bin/sh

set -e

tmp1=$(mktemp)
tmp2=$(mktemp)
tmp3=$(mktemp)

x86_64-elf-objdump -t build/krnl.sys | gsed '/\bd\b/d' | sort > "$tmp1"
grep "\.text" < "$tmp1" | cut -d' ' -f1 > "$tmp2"
grep "\.text" < "$tmp1" | gawk 'NF{ print $NF }' > "$tmp3"

cat << EOF > krnl/debug/_symtbl.map
// This file was automatically generated by utils/gensym.sh.
// Do NOT edit this file manually.

/**
 * LuxeOS (c) 2023 by Jozef Nagy
 *
 * LuxeOS is licensed under a
 * Creative Commons Attribution-NoDerivatives 4.0 International License.
 *
 * You should have received a copy of the license along with this
 * work. If not, see <http://creativecommons.org/licenses/by-nd/4.0/>.
 */

#include <debug/sym.h>

const symbol_t _symtab[] = {
EOF

paste -d'$' "$tmp2" "$tmp3" | gsed 's/^/	{ 0x/g' | gsed ' s/\$/, "/g' | gsed 's/$/"},/g' >> krnl/debug/_symtbl.map

cat << EOF >> krnl/debug/_symtbl.map
	{ 0xffffffffffffffff, ""}
};
EOF

rm -rf "$tmp1" "$tmp2" "$tmp3"